# Generated by Django 3.0.6 on 2020-05-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Craiglist', '0002_auto_20200510_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
